default_language_version:
    python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: fix-encoding-pragma
        args: ['--remove']
      - id: end-of-file-fixer
      - id: check-ast
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: detect-aws-credentials
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.0.1
    hooks:
      - id: forbid-crlf
  - repo: https://github.com/ambv/black
    rev: 21.4b1
    hooks:
      - id: black
        args: [ "--line-length=100" ]
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        entry: bash -c 'mypy "$@" || true' --
        args: [ "--no-strict-optional", "--ignore-missing-imports" ]
  - repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.56.2
    hooks:
      - id: cfn-python-lint
        files: template.yaml
