version: "3"

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - PORT=8888
    volumes:
      - .:/app
    command: /start-reload.sh
